import {
  Activity,
  BadgeCheck,
  BookCheck,
  Bot,
  BriefcaseBusiness,
  Bug,
  ClipboardCheck,
  FileInput,
  FileText,
  FlaskConical,
  FolderCog,
  KanbanSquare,
  LayoutDashboard,
  ListChecks,
  MessagesSquare,
  Rocket,
  ScanSearch,
  Sparkles,
} from "lucide-react";

export const iconMap = {
  activity: Activity,
  "badge-check": BadgeCheck,
  "book-check": BookCheck,
  bot: Bot,
  "briefcase-business": BriefcaseBusiness,
  bug: Bug,
  "clipboard-check": ClipboardCheck,
  "file-input": FileInput,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  "folder-cog": FolderCog,
  "kanban-square": KanbanSquare,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  "messages-square": MessagesSquare,
  rocket: Rocket,
  "scan-search": ScanSearch,
  sparkles: Sparkles,
};
